apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-html
  namespace: tmtd
data:
  index.html: |
    <html>
    <head>
        <title>DevOps Demo</title>
    </head>
    <body>
        <h1>Hello from Yousif DevOps 🚀</h1>
        <h2>Zero Downtime Deployment Working sapphire HQ argoCD heayyyyyyyy i am done </h2>
    </body>
    </html>
