apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-demo
  namespace: tmtd

spec:
  replicas: 2

  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1

  selector:
    matchLabels:
      app: nginx-demo

  template:
    metadata:
      labels:
        app: nginx-demo

    spec:
      containers:
      - name: nginx
        image: nginx:latest

        ports:
        - containerPort: 80
